export const uiComponents = [
  {
    id: "button",
    name: "Button",
    selector: "app-button",
    packageType: "ui",
    category: "forms",
    props: [
      {
        name: "variant",
        type: "select",
        default: "primary",
        options: ["primary", "secondary", "danger"],
      },
      {
        name: "size",
        type: "select",
        default: "md",
        options: ["sm", "md", "lg"],
      },
      { name: "disabled", type: "boolean", default: false },
    ],
    template: "<button>Button</button>",
    css: ":host { display: inline-flex; }",
  },
  {
    id: "badge",
    name: "Badge",
    selector: "app-badge",
    packageType: "ui",
    category: "display",
    props: [
      {
        name: "variant",
        type: "select",
        default: "default",
        options: ["default", "primary", "success", "warning", "danger"],
      },
      {
        name: "size",
        type: "select",
        default: "md",
        options: ["sm", "md", "lg"],
      },
    ],
    template: "<span>Badge</span>",
    css: ":host { display: inline-flex; }",
  },
  {
    id: "avatar",
    name: "Avatar",
    selector: "app-avatar",
    packageType: "ui",
    category: "display",
    props: [
      { name: "src", type: "string", default: "" },
      { name: "alt", type: "string", default: "Avatar" },
      {
        name: "size",
        type: "select",
        default: "md",
        options: ["sm", "md", "lg"],
      },
    ],
    template: '<img alt="Avatar" />',
    css: ":host { display: inline-flex; }",
  },
  {
    id: "chip",
    name: "Chip",
    selector: "app-chip",
    packageType: "ui",
    category: "display",
    props: [
      { name: "label", type: "string", default: "" },
      { name: "removable", type: "boolean", default: false },
    ],
    template: "<span>Chip</span>",
    css: ":host { display: inline-flex; }",
  },
  {
    id: "input",
    name: "Input",
    selector: "app-input",
    packageType: "ui",
    category: "forms",
    props: [
      {
        name: "type",
        type: "select",
        default: "text",
        options: ["text", "email", "password", "number"],
      },
      { name: "placeholder", type: "string", default: "" },
      { name: "disabled", type: "boolean", default: false },
    ],
    template: '<input type="text" />',
    css: ":host { display: block; }",
  },
  {
    id: "checkbox",
    name: "Checkbox",
    selector: "app-checkbox",
    packageType: "ui",
    category: "forms",
    props: [
      { name: "checked", type: "boolean", default: false },
      { name: "label", type: "string", default: "" },
    ],
    template: '<label><input type="checkbox" /> Checkbox</label>',
    css: ":host { display: block; }",
  },
  {
    id: "radio",
    name: "Radio",
    selector: "app-radio",
    packageType: "ui",
    category: "forms",
    props: [
      { name: "name", type: "string", default: "" },
      { name: "value", type: "string", default: "" },
    ],
    template: '<label><input type="radio" /> Radio</label>',
    css: ":host { display: block; }",
  },
  {
    id: "tabs",
    name: "Tabs",
    selector: "app-tabs",
    packageType: "ui",
    category: "layout",
    props: [{ name: "tabs", type: "string", default: '["Tab 1", "Tab 2"]' }],
    template: "<div><button>Tab 1</button><button>Tab 2</button></div>",
    css: ":host { display: block; }",
  },
  {
    id: "empty-state",
    name: "Empty State",
    selector: "app-empty-state",
    packageType: "ui",
    category: "display",
    props: [
      { name: "title", type: "string", default: "No data" },
      { name: "message", type: "string", default: "" },
    ],
    template: "<div><p>No data</p></div>",
    css: ":host { display: block; }",
  },
  {
    id: "loading",
    name: "Loading",
    selector: "app-loading",
    packageType: "ui",
    category: "feedback",
    props: [
      {
        name: "size",
        type: "select",
        default: "md",
        options: ["sm", "md", "lg"],
      },
    ],
    template: "<div>Loading...</div>",
    css: ":host { display: block; }",
  },
  {
    id: "pagination",
    name: "Pagination",
    selector: "app-pagination",
    packageType: "ui",
    category: "navigation",
    props: [
      { name: "page", type: "number", default: 1 },
      { name: "total", type: "number", default: 10 },
    ],
    template: "<div>Pagination</div>",
    css: ":host { display: block; }",
  },
  {
    id: "tooltip",
    name: "Tooltip",
    selector: "app-tooltip",
    packageType: "ui",
    category: "feedback",
    props: [
      { name: "text", type: "string", default: "" },
      {
        name: "position",
        type: "select",
        default: "top",
        options: ["top", "bottom", "left", "right"],
      },
    ],
    template: "<span>Tooltip</span>",
    css: ":host { display: inline-flex; }",
  },
  {
    id: "progress-bar",
    name: "Progress Bar",
    selector: "app-progress-bar",
    packageType: "ui",
    category: "feedback",
    props: [
      { name: "value", type: "number", default: 0 },
      { name: "max", type: "number", default: 100 },
    ],
    template: "<div><div>Progress</div></div>",
    css: ":host { display: block; }",
  },
  {
    id: "slider",
    name: "Slider",
    selector: "app-slider",
    packageType: "ui",
    category: "forms",
    props: [
      { name: "min", type: "number", default: 0 },
      { name: "max", type: "number", default: 100 },
      { name: "value", type: "number", default: 50 },
    ],
    template: '<input type="range" />',
    css: ":host { display: block; }",
  },
  {
    id: "select",
    name: "Select",
    selector: "app-select",
    packageType: "ui",
    category: "forms",
    props: [
      { name: "options", type: "string", default: "[]" },
      { name: "placeholder", type: "string", default: "Select..." },
    ],
    template: "<select><option>Option</option></select>",
    css: ":host { display: block; }",
  },
  {
    id: "switch",
    name: "Switch",
    selector: "app-switch",
    packageType: "ui",
    category: "forms",
    props: [{ name: "checked", type: "boolean", default: false }],
    template: '<label><input type="checkbox" /> Switch</label>',
    css: ":host { display: block; }",
  },
];
//# sourceMappingURL=components.js.map
