export const feedbackComponents = [
  {
    id: "dialog",
    name: "Dialog",
    selector: "app-dialog",
    packageType: "feedback",
    category: "feedback",
    props: [
      { name: "open", type: "boolean", default: false },
      { name: "title", type: "string", default: "" },
      {
        name: "size",
        type: "select",
        default: "md",
        options: ["sm", "md", "lg"],
      },
    ],
    template: "<div><h2>Dialog</h2><p>Content</p></div>",
    css: ":host { display: block; }",
  },
  {
    id: "confirm-dialog",
    name: "Confirm Dialog",
    selector: "app-confirm-dialog",
    packageType: "feedback",
    category: "feedback",
    props: [
      { name: "open", type: "boolean", default: false },
      { name: "title", type: "string", default: "Confirm" },
      { name: "message", type: "string", default: "Are you sure?" },
    ],
    template: "<div><h2>Confirm</h2><p>Message</p></div>",
    css: ":host { display: block; }",
  },
  {
    id: "toast",
    name: "Toast",
    selector: "app-toast",
    packageType: "feedback",
    category: "feedback",
    props: [
      { name: "message", type: "string", default: "" },
      {
        name: "type",
        type: "select",
        default: "info",
        options: ["info", "success", "warning", "error"],
      },
      { name: "duration", type: "number", default: 3000 },
    ],
    template: "<div>Toast</div>",
    css: ":host { display: block; }",
  },
  {
    id: "snackbar",
    name: "Snackbar",
    selector: "app-snackbar",
    packageType: "feedback",
    category: "feedback",
    props: [
      { name: "message", type: "string", default: "" },
      { name: "action", type: "string", default: "" },
    ],
    template: "<div>Snackbar</div>",
    css: ":host { display: block; }",
  },
  {
    id: "command-palette",
    name: "Command Palette",
    selector: "app-command-palette",
    packageType: "feedback",
    category: "feedback",
    props: [
      { name: "open", type: "boolean", default: false },
      { name: "commands", type: "string", default: "[]" },
    ],
    template: "<div>Command Palette</div>",
    css: ":host { display: block; }",
  },
  {
    id: "modal",
    name: "Modal",
    selector: "app-modal",
    packageType: "feedback",
    category: "feedback",
    props: [
      { name: "open", type: "boolean", default: false },
      { name: "title", type: "string", default: "" },
    ],
    template: "<div><h2>Modal</h2><p>Content</p></div>",
    css: ":host { display: block; }",
  },
];
//# sourceMappingURL=components.js.map
