import type { SharedComponentDef } from "./core/lib/types";

export const uiComponents: SharedComponentDef[] = [
  {
    id: "button",
    name: "Button",
    selector: "app-button",
    packageType: "ui",
    category: "forms",
    props: [
      {
        name: "variant",
        type: "select",
        default: "primary",
        options: ["primary", "secondary", "danger"],
      },
      {
        name: "size",
        type: "select",
        default: "md",
        options: ["sm", "md", "lg"],
      },
      { name: "disabled", type: "boolean", default: false },
    ],
    template: "<button>Button</button>",
    css: ":host { display: inline-flex; }",
  },
  {
    id: "badge",
    name: "Badge",
    selector: "app-badge",
    packageType: "ui",
    category: "display",
    props: [
      {
        name: "variant",
        type: "select",
        default: "default",
        options: ["default", "primary", "success", "warning", "danger"],
      },
      {
        name: "size",
        type: "select",
        default: "md",
        options: ["sm", "md", "lg"],
      },
    ],
    template: "<span>Badge</span>",
    css: ":host { display: inline-flex; }",
  },
  {
    id: "avatar",
    name: "Avatar",
    selector: "app-avatar",
    packageType: "ui",
    category: "display",
    props: [
      { name: "src", type: "string", default: "" },
      { name: "alt", type: "string", default: "Avatar" },
      {
        name: "size",
        type: "select",
        default: "md",
        options: ["sm", "md", "lg"],
      },
    ],
    template: '<img alt="Avatar" />',
    css: ":host { display: inline-flex; }",
  },
  {
    id: "chip",
    name: "Chip",
    selector: "app-chip",
    packageType: "ui",
    category: "display",
    props: [
      { name: "label", type: "string", default: "" },
      { name: "removable", type: "boolean", default: false },
    ],
    template: "<span>Chip</span>",
    css: ":host { display: inline-flex; }",
  },
  {
    id: "input",
    name: "Input",
    selector: "app-input",
    packageType: "ui",
    category: "forms",
    props: [
      {
        name: "type",
        type: "select",
        default: "text",
        options: ["text", "email", "password", "number"],
      },
      { name: "placeholder", type: "string", default: "" },
      { name: "disabled", type: "boolean", default: false },
    ],
    template: '<input type="text" />',
    css: ":host { display: block; }",
  },
  {
    id: "checkbox",
    name: "Checkbox",
    selector: "app-checkbox",
    packageType: "ui",
    category: "forms",
    props: [
      { name: "checked", type: "boolean", default: false },
      { name: "label", type: "string", default: "" },
    ],
    template: '<label><input type="checkbox" /> Checkbox</label>',
    css: ":host { display: block; }",
  },
  {
    id: "radio",
    name: "Radio",
    selector: "app-radio",
    packageType: "ui",
    category: "forms",
    props: [
      { name: "name", type: "string", default: "" },
      { name: "value", type: "string", default: "" },
    ],
    template: '<label><input type="radio" /> Radio</label>',
    css: ":host { display: block; }",
  },
  {
    id: "tabs",
    name: "Tabs",
    selector: "app-tabs",
    packageType: "ui",
    category: "layout",
    props: [{ name: "tabs", type: "string", default: '["Tab 1", "Tab 2"]' }],
    template: "<div><button>Tab 1</button><button>Tab 2</button></div>",
    css: ":host { display: block; }",
  },
  {
    id: "empty-state",
    name: "Empty State",
    selector: "app-empty-state",
    packageType: "ui",
    category: "display",
    props: [
      { name: "title", type: "string", default: "No data" },
      { name: "message", type: "string", default: "" },
    ],
    template: "<div><p>No data</p></div>",
    css: ":host { display: block; }",
  },
  {
    id: "loading",
    name: "Loading",
    selector: "app-loading",
    packageType: "ui",
    category: "feedback",
    props: [
      {
        name: "size",
        type: "select",
        default: "md",
        options: ["sm", "md", "lg"],
      },
    ],
    template: "<div>Loading...</div>",
    css: ":host { display: block; }",
  },
  {
    id: "pagination",
    name: "Pagination",
    selector: "app-pagination",
    packageType: "ui",
    category: "navigation",
    props: [
      { name: "page", type: "number", default: 1 },
      { name: "total", type: "number", default: 10 },
    ],
    template: "<div>Pagination</div>",
    css: ":host { display: block; }",
  },
  {
    id: "tooltip",
    name: "Tooltip",
    selector: "app-tooltip",
    packageType: "ui",
    category: "feedback",
    props: [
      { name: "text", type: "string", default: "" },
      {
        name: "position",
        type: "select",
        default: "top",
        options: ["top", "bottom", "left", "right"],
      },
    ],
    template: "<span>Tooltip</span>",
    css: ":host { display: inline-flex; }",
  },
  {
    id: "progress-bar",
    name: "Progress Bar",
    selector: "app-progress-bar",
    packageType: "ui",
    category: "feedback",
    props: [
      { name: "value", type: "number", default: 0 },
      { name: "max", type: "number", default: 100 },
    ],
    template: "<div><div>Progress</div></div>",
    css: ":host { display: block; }",
  },
  {
    id: "slider",
    name: "Slider",
    selector: "app-slider",
    packageType: "ui",
    category: "forms",
    props: [
      { name: "min", type: "number", default: 0 },
      { name: "max", type: "number", default: 100 },
      { name: "value", type: "number", default: 50 },
    ],
    template: '<input type="range" />',
    css: ":host { display: block; }",
  },
  {
    id: "select",
    name: "Select",
    selector: "app-select",
    packageType: "ui",
    category: "forms",
    props: [
      { name: "options", type: "string", default: "[]" },
      { name: "placeholder", type: "string", default: "Select..." },
    ],
    template: "<select><option>Option</option></select>",
    css: ":host { display: block; }",
  },
  {
    id: "switch",
    name: "Switch",
    selector: "app-switch",
    packageType: "ui",
    category: "forms",
    props: [{ name: "checked", type: "boolean", default: false }],
    template: '<label><input type="checkbox" /> Switch</label>',
    css: ":host { display: block; }",
  },
];

export const layoutComponents: SharedComponentDef[] = [
  {
    id: "split-view",
    name: "Split View",
    selector: "app-split-view",
    packageType: "layout",
    category: "layout",
    props: [
      {
        name: "direction",
        type: "select",
        default: "horizontal",
        options: ["horizontal", "vertical"],
      },
      { name: "split", type: "number", default: 50 },
    ],
    template: "<div><div>Left</div><div>Right</div></div>",
    css: ":host { display: block; }",
  },
  {
    id: "page-container",
    name: "Page Container",
    selector: "app-page-container",
    packageType: "layout",
    category: "layout",
    props: [{ name: "title", type: "string", default: "" }],
    template: "<div><h1>Page</h1><ng-content></ng-content></div>",
    css: ":host { display: block; }",
  },
  {
    id: "page-toolbar",
    name: "Page Toolbar",
    selector: "app-page-toolbar",
    packageType: "layout",
    category: "layout",
    props: [{ name: "title", type: "string", default: "" }],
    template: "<div><span>Toolbar</span></div>",
    css: ":host { display: block; }",
  },
  {
    id: "header",
    name: "Header",
    selector: "app-header",
    packageType: "layout",
    category: "layout",
    props: [
      { name: "title", type: "string", default: "" },
      { name: "breadcrumbs", type: "string", default: "" },
    ],
    template: "<header><nav>Header</nav></header>",
    css: ":host { display: block; }",
  },
  {
    id: "sidebar",
    name: "Sidebar",
    selector: "app-sidebar",
    packageType: "layout",
    category: "layout",
    props: [
      { name: "collapsed", type: "boolean", default: false },
      { name: "items", type: "string", default: "[]" },
    ],
    template: "<nav><ul><li>Item</li></ul></nav>",
    css: ":host { display: block; }",
  },
  {
    id: "footer",
    name: "Footer",
    selector: "app-footer",
    packageType: "layout",
    category: "layout",
    props: [{ name: "text", type: "string", default: "" }],
    template: "<footer><span>Footer</span></footer>",
    css: ":host { display: block; }",
  },
  {
    id: "main-editor",
    name: "Main Editor",
    selector: "app-main-editor",
    packageType: "layout",
    category: "layout",
    props: [],
    template: "<div><span>Canvas</span></div>",
    css: ":host { display: block; }",
  },
  {
    id: "bottom-panel",
    name: "Bottom Panel",
    selector: "app-bottom-panel",
    packageType: "layout",
    category: "layout",
    props: [
      { name: "tabs", type: "string", default: "[]" },
      { name: "activeTab", type: "string", default: "pages" },
    ],
    template: "<div><span>Bottom Panel</span></div>",
    css: ":host { display: block; }",
  },
  {
    id: "designer-sidebar",
    name: "Designer Sidebar",
    selector: "app-designer-sidebar",
    packageType: "layout",
    category: "designer",
    props: [
      {
        name: "position",
        type: "select",
        default: "left",
        options: ["left", "right"],
      },
      { name: "collapsed", type: "boolean", default: false },
      { name: "header", type: "string", default: "" },
    ],
    template: '<aside><slot name="content"></slot></aside>',
    css: ":host { display: block; }",
  },
  {
    id: "component-palette",
    name: "Component Palette",
    selector: "app-component-palette",
    packageType: "layout",
    category: "designer",
    props: [
      { name: "selectedCategory", type: "string", default: "all" },
      { name: "searchable", type: "boolean", default: true },
    ],
    template: "<div><span>Palette</span></div>",
    css: ":host { display: block; }",
  },
  {
    id: "canvas",
    name: "Canvas",
    selector: "app-canvas",
    packageType: "layout",
    category: "designer",
    props: [
      { name: "gridColumns", type: "number", default: 12 },
      { name: "showGrid", type: "boolean", default: true },
      { name: "selectedId", type: "string", default: "" },
    ],
    template: "<div><span>Canvas</span></div>",
    css: ":host { display: block; }",
  },
  {
    id: "canvas-toolbar",
    name: "Canvas Toolbar",
    selector: "app-canvas-toolbar",
    packageType: "layout",
    category: "designer",
    props: [],
    template: "<div></div>",
    css: ":host { display: inline-flex; }",
  },
];

export const feedbackComponents: SharedComponentDef[] = [
  {
    id: "dialog",
    name: "Dialog",
    selector: "app-dialog",
    packageType: "feedback",
    category: "feedback",
    props: [
      { name: "open", type: "boolean", default: false },
      { name: "title", type: "string", default: "" },
      {
        name: "size",
        type: "select",
        default: "md",
        options: ["sm", "md", "lg"],
      },
    ],
    template: "<div><h2>Dialog</h2><p>Content</p></div>",
    css: ":host { display: block; }",
  },
  {
    id: "confirm-dialog",
    name: "Confirm Dialog",
    selector: "app-confirm-dialog",
    packageType: "feedback",
    category: "feedback",
    props: [
      { name: "open", type: "boolean", default: false },
      { name: "title", type: "string", default: "Confirm" },
      { name: "message", type: "string", default: "Are you sure?" },
    ],
    template: "<div><h2>Confirm</h2><p>Message</p></div>",
    css: ":host { display: block; }",
  },
  {
    id: "toast",
    name: "Toast",
    selector: "app-toast",
    packageType: "feedback",
    category: "feedback",
    props: [
      { name: "message", type: "string", default: "" },
      {
        name: "type",
        type: "select",
        default: "info",
        options: ["info", "success", "warning", "error"],
      },
      { name: "duration", type: "number", default: 3000 },
    ],
    template: "<div>Toast</div>",
    css: ":host { display: block; }",
  },
  {
    id: "snackbar",
    name: "Snackbar",
    selector: "app-snackbar",
    packageType: "feedback",
    category: "feedback",
    props: [
      { name: "message", type: "string", default: "" },
      { name: "action", type: "string", default: "" },
    ],
    template: "<div>Snackbar</div>",
    css: ":host { display: block; }",
  },
  {
    id: "command-palette",
    name: "Command Palette",
    selector: "app-command-palette",
    packageType: "feedback",
    category: "feedback",
    props: [
      { name: "open", type: "boolean", default: false },
      { name: "commands", type: "string", default: "[]" },
    ],
    template: "<div>Command Palette</div>",
    css: ":host { display: block; }",
  },
  {
    id: "modal",
    name: "Modal",
    selector: "app-modal",
    packageType: "feedback",
    category: "feedback",
    props: [
      { name: "open", type: "boolean", default: false },
      { name: "title", type: "string", default: "" },
    ],
    template: "<div><h2>Modal</h2><p>Content</p></div>",
    css: ":host { display: block; }",
  },
];

export const dataComponents: SharedComponentDef[] = [
  {
    id: "card",
    name: "Card",
    selector: "app-card",
    packageType: "data",
    category: "display",
    props: [
      { name: "title", type: "string", default: "" },
      { name: "content", type: "string", default: "" },
      { name: "elevated", type: "boolean", default: false },
    ],
    template: "<div><h3>Card Title</h3><p>Card content</p></div>",
    css: ":host { display: block; }",
  },
  {
    id: "stats-card",
    name: "Stats Card",
    selector: "app-stats-card",
    packageType: "data",
    category: "display",
    props: [
      { name: "label", type: "string", default: "" },
      { name: "value", type: "string", default: "" },
      { name: "icon", type: "string", default: "" },
    ],
    template: "<div><span>0</span><span>Label</span></div>",
    css: ":host { display: block; }",
  },
  {
    id: "table-view",
    name: "Table View",
    selector: "app-table-view",
    packageType: "data",
    category: "display",
    props: [
      { name: "columns", type: "string", default: "[]" },
      { name: "data", type: "string", default: "[]" },
    ],
    template: "<table><thead></thead><tbody></tbody></table>",
    css: ":host { display: block; }",
  },
  {
    id: "data-table",
    name: "Data Table",
    selector: "app-data-table",
    packageType: "data",
    category: "display",
    props: [
      { name: "columns", type: "string", default: "[]" },
      { name: "data", type: "string", default: "[]" },
      { name: "selectable", type: "boolean", default: false },
    ],
    template: "<table><thead></thead><tbody></tbody></table>",
    css: ":host { display: block; }",
  },
  {
    id: "json-view",
    name: "JSON View",
    selector: "app-json-view",
    packageType: "data",
    category: "display",
    props: [{ name: "data", type: "string", default: "{}" }],
    template: "<pre>{}</pre>",
    css: ":host { display: block; }",
  },
  {
    id: "segment-selector",
    name: "Segment Selector",
    selector: "app-segment-selector",
    packageType: "data",
    category: "forms",
    props: [
      { name: "options", type: "string", default: "[]" },
      { name: "selected", type: "string", default: "" },
    ],
    template: "<div><button>Option</button></div>",
    css: ":host { display: block; }",
  },
];

export const components = uiComponents;
