import type { SharedComponentDef } from "./core/lib/types";

// UI Components
export const uiComponents: SharedComponentDef[] = [
  {
    id: "avatar",
    name: "AppAvatar",
    selector: "app-avatar",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "badge",
    name: "AppBadge",
    selector: "app-badge",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "bottom-panel",
    name: "AppBottomPanel",
    selector: "app-bottom-panel",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "button",
    name: "AppButton",
    selector: "app-button",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "canvas",
    name: "AppCanvas",
    selector: "app-canvas",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "card",
    name: "AppCard",
    selector: "app-card",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "checkbox",
    name: "AppCheckbox",
    selector: "app-checkbox",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "chip",
    name: "AppChip",
    selector: "app-chip",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "component-palette",
    name: "AppComponentPalette",
    selector: "app-component-palette",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "confirm-dialog",
    name: "AppConfirmDialog",
    selector: "app-confirm-dialog",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "data-table",
    name: "AppDataTable",
    selector: "app-data-table",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "dialog",
    name: "AppDialog",
    selector: "app-dialog",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "empty-state",
    name: "AppEmptyState",
    selector: "app-empty-state",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "footer",
    name: "AppFooter",
    selector: "app-footer",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "header",
    name: "AppHeader",
    selector: "app-header",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "input",
    name: "AppInput",
    selector: "app-input",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "json-view",
    name: "AppJsonView",
    selector: "app-json-view",
    packageType: "shared",
    category: "layout",
  },
  {
    id: "loading",
    name: "AppLoading",
    selector: "app-loading",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "modal",
    name: "AppModal",
    selector: "app-modal",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "page-container",
    name: "AppPageContainer",
    selector: "app-page-container",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "page-toolbar",
    name: "AppPageToolbar",
    selector: "app-page-toolbar",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "pagination",
    name: "AppPagination",
    selector: "app-pagination",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "progress-bar",
    name: "AppProgressBar",
    selector: "app-progress-bar",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "properties-panel",
    name: "AppPropertiesPanel",
    selector: "app-properties-panel",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "radio",
    name: "AppRadio",
    selector: "app-radio",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "segment-selector",
    name: "AppSegmentSelector",
    selector: "app-segment-selector",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "select",
    name: "AppSelect",
    selector: "app-select",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "sidebar",
    name: "AppSidebar",
    selector: "app-sidebar",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "slider",
    name: "AppSlider",
    selector: "app-slider",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "split-view",
    name: "AppSplitView",
    selector: "app-split-view",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "spinner",
    name: "AppSpinner",
    selector: "app-spinner",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "stats-card",
    name: "AppStatsCard",
    selector: "app-stats-card",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "switch",
    name: "AppSwitch",
    selector: "app-switch",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "table-view",
    name: "AppTableView",
    selector: "app-table-view",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "tabs",
    name: "AppTabs",
    selector: "app-tabs",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "textarea",
    name: "AppTextarea",
    selector: "app-textarea",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "tooltip",
    name: "AppTooltip",
    selector: "app-tooltip",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "theme-toggle",
    name: "AppThemeToggle",
    selector: "app-theme-toggle",
    packageType: "shared",
    category: "layout",
  },
  {
    id: "icon",
    name: "AppIcon",
    selector: "app-icon",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "text-input",
    name: "AppTextInput",
    selector: "app-text-input",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "language-selector",
    name: "AppLanguageSelector",
    selector: "app-language-selector",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "shortcuts-overlay",
    name: "AppShortcutsOverlay",
    selector: "app-shortcuts-overlay",
    packageType: "shared",
    category: "layout",
  },
  {
    id: "translation-output",
    name: "AppTranslationOutput",
    selector: "app-translation-output",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "tree",
    name: "AppTree",
    selector: "app-tree",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "divider",
    name: "AppDivider",
    selector: "app-divider",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "form",
    name: "AppForm",
    selector: "app-form",
    packageType: "shared",
    category: "forms",
  },
];

// Layout Components
export const layoutComponents: SharedComponentDef[] = [
  {
    id: "canvas-toolbar",
    name: "CanvasToolbar",
    selector: "app-canvas-toolbar",
    packageType: "shared",
    category: "forms",
  },
  {
    id: "designer-sidebar",
    name: "DesignerSidebar",
    selector: "app-designer-sidebar",
    packageType: "shared",
    category: "forms",
  },
];

// Feedback Components
export const feedbackComponents: SharedComponentDef[] = [
  {
    id: "command-palette",
    name: "AppCommandPalette",
    selector: "app-command-palette",
    packageType: "shared",
    category: "feedback",
  },
  {
    id: "toast",
    name: "AppToast",
    selector: "app-toast",
    packageType: "shared",
    category: "feedback",
  },
  {
    id: "snackbar",
    name: "AppSnackbar",
    selector: "app-snackbar",
    packageType: "shared",
    category: "forms",
  },
];

export const components = uiComponents;
