import type { SharedComponentDef } from "./types.js";

export const layoutComponents: SharedComponentDef[] = [
  {
    id: "split-view",
    name: "Split View",
    selector: "app-split-view",
    packageType: "layout",
    category: "layout",
    props: [
      {
        name: "direction",
        type: "select",
        default: "horizontal",
        options: ["horizontal", "vertical"],
      },
      { name: "split", type: "number", default: 50 },
    ],
    template: "<div><div>Left</div><div>Right</div></div>",
    css: ":host { display: block; }",
  },
  {
    id: "page-container",
    name: "Page Container",
    selector: "app-page-container",
    packageType: "layout",
    category: "layout",
    props: [{ name: "title", type: "string", default: "" }],
    template: "<div><h1>Page</h1><ng-content></ng-content></div>",
    css: ":host { display: block; }",
  },
  {
    id: "page-toolbar",
    name: "Page Toolbar",
    selector: "app-page-toolbar",
    packageType: "layout",
    category: "layout",
    props: [{ name: "title", type: "string", default: "" }],
    template: "<div><span>Toolbar</span></div>",
    css: ":host { display: block; }",
  },
  {
    id: "header",
    name: "Header",
    selector: "app-header",
    packageType: "layout",
    category: "layout",
    props: [
      { name: "title", type: "string", default: "" },
      { name: "breadcrumbs", type: "string", default: "" },
    ],
    template: "<header><nav>Header</nav></header>",
    css: ":host { display: block; }",
  },
  {
    id: "sidebar",
    name: "Sidebar",
    selector: "app-sidebar",
    packageType: "layout",
    category: "layout",
    props: [
      { name: "collapsed", type: "boolean", default: false },
      { name: "items", type: "string", default: "[]" },
    ],
    template: "<nav><ul><li>Item</li></ul></nav>",
    css: ":host { display: block; }",
  },
  {
    id: "footer",
    name: "Footer",
    selector: "app-footer",
    packageType: "layout",
    category: "layout",
    props: [{ name: "text", type: "string", default: "" }],
    template: "<footer><span>Footer</span></footer>",
    css: ":host { display: block; }",
  },
  {
    id: "main-editor",
    name: "Main Editor",
    selector: "app-main-editor",
    packageType: "layout",
    category: "layout",
    props: [],
    template: "<div><span>Canvas</span></div>",
    css: ":host { display: block; }",
  },
  {
    id: "bottom-panel",
    name: "Bottom Panel",
    selector: "app-bottom-panel",
    packageType: "layout",
    category: "layout",
    props: [
      { name: "tabs", type: "string", default: "[]" },
      { name: "activeTab", type: "string", default: "pages" },
    ],
    template: "<div><span>Bottom Panel</span></div>",
    css: ":host { display: block; }",
  },
  {
    id: "properties-panel",
    name: "Properties Panel",
    selector: "app-properties-panel",
    packageType: "layout",
    category: "layout",
    props: [{ name: "element", type: "string", default: "{}" }],
    template: "<div><span>Properties</span></div>",
    css: ":host { display: block; }",
  },
];
